import { TaskType } from "../../types/task";
import { scheduleTasks } from "./scheduler";

// Example tasks


const tasks: TaskType[] = [
  // High priority tasks
  {
    id: "1",
    title: "Team Strategy Meeting",
    description: "Quarterly planning session",
    priority: "high",
    category: "meetings",
    completed: false,
    scheduled: false,
    date: new Date("2025-04-28T09:00:00Z"),
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 120,
    status: "todo",
  },
  {
    id: "2",
    title: "Client Presentation",
    description: "Present project milestones",
    priority: "high",
    category: "meetings",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 90,
    status: "todo",
  },
  {
    id: "3",
    title: "Critical Bug Fix",
    description: "Fix production issue",
    priority: "high",
    category: "development",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 60,
    status: "todo",
  },
  {
    id: "4",
    title: "Security Audit",
    description: "Review system security",
    priority: "high",
    category: "security",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 180,
    status: "todo",
  },
  // Medium priority tasks
  {
    id: "5",
    title: "Code Review",
    description: "Review PR #123",
    priority: "medium",
    category: "development",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 90,
    status: "todo",
  },
  {
    id: "6",
    title: "Sprint Planning",
    description: "Plan next sprint tasks",
    priority: "medium",
    category: "meetings",
    completed: false,
    scheduled: false,
    date: new Date("2025-04-29T10:00:00Z"),
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 120,
    status: "todo",
  },
  {
    id: "7",
    title: "API Documentation",
    description: "Update API endpoints docs",
    priority: "medium",
    category: "documentation",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 150,
    status: "todo",
  },
  {
    id: "8",
    title: "Team Training",
    description: "New tool training session",
    priority: "medium",
    category: "training",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 120,
    status: "todo",
  },
  {
    id: "9",
    title: "Performance Review",
    description: "Review system metrics",
    priority: "medium",
    category: "maintenance",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 90,
    status: "todo",
  },
  // Low priority tasks
  {
    id: "10",
    title: "Update Documentation",
    description: "Update user guides",
    priority: "low",
    category: "documentation",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 120,
    status: "todo",
  },
  {
    id: "11",
    title: "Code Cleanup",
    description: "Refactor legacy code",
    priority: "low",
    category: "development",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 180,
    status: "todo",
  },
  {
    id: "12",
    title: "Write Blog Post",
    description: "Technical blog post",
    priority: "low",
    category: "content",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 120,
    status: "todo",
  },
  {
    id: "13",
    title: "Team Social",
    description: "Virtual team building",
    priority: "low",
    category: "social",
    completed: false,
    scheduled: false,
    date: new Date("2025-04-30T15:00:00Z"),
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 60,
    status: "todo",
  },
  // Additional tasks with mixed priorities
  {
    id: "14",
    title: "Database Backup",
    description: "Weekly backup routine",
    priority: "high",
    category: "maintenance",
    completed: false,
    scheduled: false,
    date: new Date("2025-04-28T23:00:00Z"),
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 60,
    status: "todo",
  },
  {
    id: "15",
    title: "UI Design Review",
    description: "Review new UI mockups",
    priority: "medium",
    category: "design",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 90,
    status: "todo",
  },
  {
    id: "16",
    title: "License Updates",
    description: "Update software licenses",
    priority: "low",
    category: "admin",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 45,
    status: "todo",
  },
  {
    id: "17",
    title: "Vendor Meeting",
    description: "Discuss contract renewal",
    priority: "high",
    category: "meetings",
    completed: false,
    scheduled: false,
    date: new Date("2025-04-29T14:00:00Z"),
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 60,
    status: "todo",
  },
  {
    id: "18",
    title: "Code Workshop",
    description: "Best practices workshop",
    priority: "medium",
    category: "training",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 180,
    status: "todo",
  },
  {
    id: "19",
    title: "Project Timeline",
    description: "Update project roadmap",
    priority: "medium",
    category: "planning",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 90,
    status: "todo",
  },
  {
    id: "20",
    title: "Team Feedback",
    description: "Collect sprint feedback",
    priority: "low",
    category: "meetings",
    completed: false,
    scheduled: false,
    date: null,
    parentId: null,
    resources: [],
    startTime: null,
    endTime: null,
    duration: 60,
    status: "todo",
  },
];

// Example 1: Schedule only unscheduled tasks
console.log("Example 1: Schedule unscheduled tasks");
const unscheduledResult = scheduleTasks(tasks, {
  taskSelectionMode: "unscheduled",
  timePeriod: { type: "today" },
  optimization: {
    respectFixedAppointments: true,
    addBreaks: {
      enabled: true,
      lunchBreak: {
        start: "12:00",
        duration: 60,
      },
    },
    optimizeFocusTime: true,
  },
});
console.log("Scheduled tasks:", unscheduledResult);

// Example 2: Reschedule tasks for better efficiency
console.log("\nExample 2: Optimize existing schedule");
const rescheduledResult = scheduleTasks(tasks, {
  taskSelectionMode: "reschedule",
  timePeriod: {
    type: "this_week",
  },
  optimization: {
    respectFixedAppointments: false,
    addBreaks: {
      enabled: true,
      lunchBreak: {
        start: "12:00",
        duration: 60,
      },
      shortBreaks: {
        frequency: 120,
        duration: 15,
      },
    },
    optimizeFocusTime: true,
  },
});
console.log("Rescheduled tasks:", rescheduledResult);

// Example 3: Schedule with custom date range
console.log("\nExample 3: Schedule with custom date range");
const customResult = scheduleTasks(tasks, {
  taskSelectionMode: "full",
  timePeriod: {
    type: "custom",
    customRange: {
      start: new Date("2025-04-29T00:00:00Z"),
      end: new Date("2025-04-30T23:59:59Z"),
    },
  },
  optimization: {
    respectFixedAppointments: true,
    addBreaks: {
      enabled: true,
      lunchBreak: {
        start: "12:00",
        duration: 60,
      },
    },
    optimizeFocusTime: true,
  },
});
console.log("Custom scheduled tasks:", customResult);
